before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/ethereum-wallets-exporter.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
nfpms:
  - vendor: Evan Scott
    maintainer: Evan <evanscottkanga@gmail.com>
    formats:
      - deb
      - rpm
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
